package cs2810.group30.oaxacabackend.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**An Allergens class that attaches themselves to a Menu item.
 *
 * @author Philip Bogaars
 */
@Entity
public class Allergens {

    /**Empty constructor for the autowiring
     *
     */
    public Allergens() {

    }

    /**Full constructor taking in a (String menuid, boolean molluscs, boolean eggs, boolean fish, boolean lupin,
     boolean soy, boolean milk, boolean peanuts, boolean gluten, boolean crustaceans,
     boolean mustard, boolean nuts, boolean sesame, boolean celery, boolean sulphates
     *
     * @param menuid The id of the menuiD (usually autogenerated).
     * @param molluscs A type of Allergen.
     * @param eggs A type of Allergen.
     * @param fish A type of Allergen.
     * @param soy A type of Allergen.
     * @param milk A type of Allergen.
     * @param peanuts A type of Allergen.
     * @param gluten A type of Allergen.
     * @param mustard A type of Allergen.
     * @param nuts A type of Allergen.
     * @param sesame A type of Allergen.
     * @param celery A type of Allergen.
     * @param sulphates A type of Allergen.
     */
    public Allergens(String menuid, boolean molluscs, boolean eggs, boolean fish, boolean lupin,
                     boolean soy, boolean milk, boolean peanuts, boolean gluten, boolean crustaceans,
                     boolean mustard, boolean nuts, boolean sesame, boolean celery, boolean sulphates) {
        this.menuid = menuid;
        Molluscs = molluscs;
        Eggs = eggs;
        Fish = fish;
        Lupin = lupin;
        Soybeans = soy;
        Milk = milk;
        Peanuts = peanuts;
        cerealsGluten = gluten;
        Crustaceans = crustaceans;
        Mustard = mustard;
        treeNuts = nuts;
        Sesame = sesame;
        Celery = celery;
        Sulphites = sulphates;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public String menuid;
    boolean Molluscs,Eggs,Fish,Lupin, Soybeans,Milk,Peanuts,cerealsGluten,Crustaceans,Mustard, treeNuts,Sesame,Celery,Sulphites;

    @Id
    public String getMenuid() {
        return menuid;
    }

    public void setMenuid(String menuid) {
        this.menuid = menuid;
    }

    public boolean isMolluscs() {
        return Molluscs;
    }

    public void setMolluscs(boolean molluscs) {
        Molluscs = molluscs;
    }

    public boolean isEggs() {
        return Eggs;
    }

    public void setEggs(boolean eggs) {
        Eggs = eggs;
    }

    public boolean isFish() {
        return Fish;
    }

    public void setFish(boolean fish) {
        Fish = fish;
    }

    public boolean isLupin() {
        return Lupin;
    }

    public void setLupin(boolean lupin) {
        Lupin = lupin;
    }

    public boolean isSoybeans() {
        return Soybeans;
    }

    public void setSoybeans(boolean soybeans) {
        Soybeans = soybeans;
    }

    public boolean isMilk() {
        return Milk;
    }

    public void setMilk(boolean milk) {
        Milk = milk;
    }

    public boolean isPeanuts() {
        return Peanuts;
    }

    public void setPeanuts(boolean peanuts) {
        Peanuts = peanuts;
    }

    public boolean isCerealsGluten() {
        return cerealsGluten;
    }

    public void setCerealsGluten(boolean cerealsGluten) {
        this.cerealsGluten = cerealsGluten;
    }

    public boolean isCrustaceans() {
        return Crustaceans;
    }

    public void setCrustaceans(boolean crustaceans) {
        Crustaceans = crustaceans;
    }

    public boolean isMustard() {
        return Mustard;
    }

    public void setMustard(boolean mustard) {
        Mustard = mustard;
    }

    public boolean isTreeNuts() {
        return treeNuts;
    }

    public void setTreeNuts(boolean treeNuts) {
        this.treeNuts = treeNuts;
    }

    public boolean isSesame() {
        return Sesame;
    }

    public void setSesame(boolean sesame) {
        Sesame = sesame;
    }

    public boolean isCelery() {
        return Celery;
    }

    public void setCelery(boolean celery) {
        Celery = celery;
    }

    public boolean isSulphites() {
        return Sulphites;
    }

    public void setSulphites(boolean sulphites) {
        Sulphites = sulphites;
    }
}
