package cs2810.group30.oaxacabackend.models;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import java.sql.Timestamp;

/**An Assistance object, has it's own Id, and is associated with a tableNo, holds the time the request was made.
 *
 * @author Mostafa
 */
@Entity
public class Assistance {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String id;
    private int tableNo;
    private Timestamp timeOfRequest;

    /**Empty constructor for autowirer.
     *
     */
    public Assistance(){}

    /**Full constructor taking a String id, int tableNo, and Timestamp timeOfRequest.
     * @param id The id of the Assistance object (usually autogenerated).
     * @param tableNo The tableNo the assistance is attached too.
     * @param timeOfRequest The time that the request was placed.
     */
    public Assistance(String id, int tableNo, Timestamp timeOfRequest) {
        this.id = id;
        this.tableNo = tableNo;
        this.timeOfRequest = timeOfRequest;
    }

    @Id
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getTableNo() {
        return tableNo;
    }

    public void setTableNo(int tableNo) {
        this.tableNo = tableNo;
    }

    public Timestamp getTimeOfRequest() {
        return timeOfRequest;
    }

    public void setTimeOfRequest(Timestamp timeOfRequest) {
        this.timeOfRequest = timeOfRequest;
    }
}
