package cs2810.group30.oaxacabackend.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**A Menu object.
 *
 * @author Philip Bogaars
 */
@Entity
public class Menu {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String menuid;
    private String pname;
    private String description;
    private int calories;
    private float price;
    private String ingredients ;

    private Boolean availability;
    private String course;

    /**Empty constructor used by auto-wirer
     *
     */
    public Menu() {

    }
    @Id
    public String getMenuid() {
        return menuid;
    }

    public void setMenuid(String menuId) {
        this.menuid = menuId;
    }

    public String getPname() {
        return pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getCalories() {
        return calories;
    }

    public void setCalories(int calories) {
        this.calories = calories;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public String getIngredients() {
        return ingredients;
    }

    public void setIngredients(String ingredients) {
        this.ingredients = ingredients;
    }

    public Boolean getAvailability() {
        return availability;
    }

    public void setAvailability(Boolean availability) {
        this.availability = availability;
    }

    public String getCourse() {
        return course;
    }

    public void setCourse(String course) {
        this.course = course;
    }

    /**Full Constructor, taking a String menuId, String pname, String description, int calories, float price, String ingredients, Boolean availability, String course.
     *
     * @param menuId the id of the model (usually autogenerated).
     * @param pname the name of the menu object.
     * @param description a description of the menu object.
     * @param calories an int representing the calories in the menu object.
     * @param price a float representing the price when the order was placed.
     * @param ingredients the ingredients of the menu object.
     * @param availability boolean of the availability of the menu object.
     * @param course a string of the type of course the menu object is(Starter,Main,Dessert).
     */
    public Menu(String menuId, String pname, String description, int calories, float price, String ingredients, Boolean availability, String course) {
        this.menuid = menuId;
        this.pname = pname;
        this.description = description;
        this.calories = calories;
        this.price = price;
        this.ingredients = ingredients;
        this.availability = availability;
        this.course = course;
    }

}
