package cs2810.group30.oaxacabackend.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**An OrderItem that attach themselves to an Order.
 *
 * @author Mostafa
 */
@Entity
public class OrderItem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String itemId;
    private String name;
    private String orderId;
    private String menuId;
    private int quantity;
    private String notes;

    /**Empty constructor for the autowiring
     *
     */
    public OrderItem() {
    }

    /**Full constructor taking in a String item Id, String name of the menu item, String orderId, String menuId, int quantity, and String of other notes.
     *
     * @param itemId The ID of the itemID (usually autogenerated).
     * @param name The name of the menu item when the order is placed.
     * @param orderId The ID of the order the orderItem is attached too.
     * @param menuId The Menu ID of the item in the order.
     * @param quantity The quantity of that item.
     * @param notes Notes detailing any customisation (eg. no ice).
     */
    public OrderItem(String itemId, String name, String orderId, String menuId, int quantity, String notes) {
        this.itemId = itemId;
        this.name = name;
        this.orderId = orderId;
        this.menuId = menuId;
        this.quantity = quantity;
        this.notes = notes;
    }

    @Id
    public String getItemId() {
        return itemId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getMenuId() {
        return menuId;
    }

    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
